apiVersion: v1
kind: Service
metadata:
  name: piler-memcached
  labels:
    app: piler-memcached
spec:
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
  selector:
    app: piler-memcached